import React, { useState, useEffect } from "react";
import { useRouter } from 'next/router';
import Head from 'next/head';
import CssBaseline from '@mui/material/CssBaseline';
import NextLink from 'next/link';
import Image from 'next/image';
import Grid from '@mui/material/Divider';
import Layout from "../Layout";
import { makeStyles } from '@mui/styles';
import Container from '@mui/material/Container';
import Loading from "../loading/loading";
import useStyles from './style';
import Typography from '@mui/material/Typography';


const IMAGE_API = "https://image.tmdb.org/t/p/w1280";


function MovieInfo({ Data }) {
  const [movies, setMovies] = useState([]);
  const [showIntro, setShowIntro] = useState(true);
  const [isLoading, setIsLoading] = useState(true);
  const classes = useStyles();
 
    

  return (
  <>
   <Head>
       <title>{Data.title}</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
       <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous"/>  
    </Head> 

  <Layout >   
  
  <div style={{ width:'100vw',position:'relative' }} >
      
    <img src={IMAGE_API + Data.backdrop_path}  style={{
        width:'100vw',
        height: '100%'
         }}/>
    <div style={{backgroundColor: 'rgba(0,0,0,0.7)',
        position: 'absolute',
        top: '0%',
        width: '100%',
        height: '100%',
        color: 'white',
        display: "flex",
        paddingTop: '10rem', }}>
      
       <div style={{ width:'30%',}}>
        
        {Data.poster_path ? (
           <img src={IMAGE_API + Data.poster_path} alt={Data.title} style={{ width:'13rem',
           position: 'absolute',
           left: '0',
           marginLeft: '4%',}}/>
        ) : (
        <img src="no-cover.png" alt={Data.title} />
         )}
       </div> 
       <div style={{ width:'50%'}}>
       <Typography variant="h4" gutterBottom component="div">
          {Data.title}
      </Typography>
      <Typography variant="h6" gutterBottom component="div" style={{color:'#4d4d4d'}}>
      {Data.release_date}
      </Typography>
      <Typography variant="subtitle1" gutterBottom component="div" style={{ width:'60%'}}>
      {Data.overview}
      </Typography>
          
       </div>
      
    </div>
    
  </div>
  
  </Layout>  
 
  </>
)
}

export default MovieInfo;

