import React, { useState, useEffect } from "react";
import { useRouter } from 'next/router';
import Head from 'next/head';
import CssBaseline from '@mui/material/CssBaseline';
import NextLink from 'next/link';
import Image from 'next/image';
import Grid from '@mui/material/Divider';
import Typography from '@mui/material/Divider';
import Layout from "../../component/Layout";
import { makeStyles } from '@mui/styles';
import Container from '@mui/material/Container';
import Loading from "../../component/loading/loading";


const useStyles = makeStyles((theme) => ({
    detailMovie:{
        width:'100vw',
        position:'relative',
    },
    grid:{
        backgroundColor: 'rgba(0,0,0,0.7)',
        position: 'absolute',
        top: '0%',
        width: '100%',
        height: '100%',
        color: 'white',
        display: "flex",
        paddingTop: '5rem',
    },

    backGround:{
        width:'100vw',
        height: '100%',
    },
    contImg:{
        width:'30%',
    },
    img:{
        width:'13rem',
        position: 'absolute',
        left: '0',
        marginLeft: '4%',
    },
    discMovie:{
        width:'50%',
    },
    prg:{
        width:'60%',
    },
    leftSide:{
        display: "flex",
        alignItems: "center",
        color:"white",
        justifyContent: "space-around",
    },
    iconSearch:{
        color:"white",
        fontSize: "1.4rem",
    },
    rightSide:{
        display: "flex",
        justifyContent: "space-around",
    },
	btnRgst:{
        background:' white',
        border: 'none',
        color: 'black',
        fontWeight: 'bold',
        '&:hover':{
            background:'white', 
        }
    },
    btnSng:{
        color: 'white',
    },
}));

const IMAGE_API = "https://image.tmdb.org/t/p/w1280";

function detailMovie() {
    const classes = useStyles();
    const [movies, setMovies] = useState([]);
    const [showIntro, setShowIntro] = useState(true);
    const [isLoading, setIsLoading] = useState(true);
    const router = useRouter();
    const  id  = router.query.id;
    const movieId =
    "https://api.themoviedb.org/3/movie/"+id+"?api_key=e210177d339cffde80c7bde18b504e93";
   

    const getMovies = (Id) => {
        fetch(Id)
        .then((res) => res.json())
        .then((data) => setMovies(data));
      };

      useEffect(() => {
        getMovies(movieId);
      }, []);


      useEffect(() => {
        const timer = setTimeout(() => {
          setShowIntro(false);
          setIsLoading(false)
        }, 4500)
    
        return (() => clearTimeout(timer));
      });
    
    
      if (isLoading) {
        return <Loading />
      }
      

    return (
    <>
     <Head>
         <title>{movies.title}</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
         <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous"/>  
      </Head> 
      {!showIntro && 
    <Layout>   
    
    <div className={classes.detailMovie} >
        
      <img src={IMAGE_API + movies.backdrop_path}  className={classes.backGround}/>
      <div className={classes.grid} >
        
         <div className={classes.contImg} >
          
          {movies.poster_path ? (
             <img src={IMAGE_API + movies.poster_path} alt={movies.title} className={classes.img}/>
          ) : (
          <img src="no-cover.png" alt={movies.title} />
           )}
         </div> 
         <div className={classes.discMovie}>
            <h2>{movies.title}</h2>
            <h6 style={{color:'#4d4d4d'}}>{movies.release_date}</h6>
            <p className={classes.prg}>{movies.overview}</p>
         </div>
        
      </div>
      
    </div>
    
    </Layout>  
    }
    </>
  )
}

export default detailMovie