import React, { useState, useEffect } from "react";
import { useRouter } from 'next/router';
import Head from 'next/head';
import CssBaseline from '@mui/material/CssBaseline';
import NextLink from 'next/link';
import Image from 'next/image';
import Grid from '@mui/material/Divider';
import Layout from "../../component/Layout";
import { makeStyles } from '@mui/styles';
import Container from '@mui/material/Container';
import Loading from "../../component/loading/loading";
import useStyles from './style';
import Typography from '@mui/material/Typography';
import MovieInfo from "../../component/movieInfo/movieInfo";


const IMAGE_API = "https://image.tmdb.org/t/p/w1280";



export async function getServerSideProps({ query }) {
  let Name = await fetch(
    `https://api.themoviedb.org/3/movie/${query.id}?api_key=512f02bfeaad808b483c6f3bb546db74`
  );
  let Data = await Name.json();
  return {
    props: {
      Data,
    },
  };
}


function DetailMovie({ Data }) {
  const [movies, setMovies] = useState([]);
  const [showIntro, setShowIntro] = useState(true);
  const [isLoading, setIsLoading] = useState(true);
  const classes = useStyles();
 
    

  return (
  <>
   <Head>
       <title>{Data.title}</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
       <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous"/>  
    </Head> 

  <>   
  
  <MovieInfo Data={Data}/>
  </>  
 
  </>
)
}

export default DetailMovie;

