import React, { useEffect, useState} from 'react';
import "react-multi-carousel/lib/styles.css";
import Movies from "../component/movies";
import MoviesObj from "../component/TMDB";
import Banner from "../component/banner/banner";
import Loading from "../component/loading/loading";
import Head from 'next/head';
import Layout from '../component/Layout';



export default function Home() {
  const [showIntro, setShowIntro] = useState(true);
  const [isLoading, setIsLoading] = useState(true);


  useEffect(() => {
    const timer = setTimeout(() => {
      setShowIntro(false);
      setIsLoading(false)
    }, 4500)

    return (() => clearTimeout(timer));
  });


  if (isLoading) {
    return <Loading title={'molla'}/>
  }
  

  return (
    <div>
    <Head>
    <title>molla</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous"/>  
 </Head> 

    {!showIntro && 
 
      <Layout>
        <Banner />
        {MoviesObj.map((Obj, Ind) => {
         return <Movies link={Obj.Request} genre={Obj.Title} key={Ind}/>;
      })}
      </Layout>
     }
    </div>
  )
}


