import React from 'react';
import Head from 'next/head';
import CssBaseline from '@mui/material/CssBaseline';
import Footer from './footer/footer' 
import Navbar from './navbar/navbar' 


export default function Layout({children }) {
  


  return (
    <div>
      <Head>
         <title>cart</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
         <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous"/>  
      </Head>
      
        <CssBaseline />
        <Navbar />
        {children}
	      <Footer />
      
      
    </div>
  );
}